swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: User Transaction API
      description: API for fetching all user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile/transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: User Transaction API
      description: API for fetching one user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: path
          name: id
          type: integer
          required: true
          description: "ID of the transaction to get"
      produces:
        - application/json
      responses:
        "200":
          description: User Transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: User Transaction API
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: path
          name: id
          type: integer
          required: true
          description: "ID of the transaction to get"
        - in: body
          name: body
          description: Update user transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/TransactionUpdate"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: User Transaction API
      description: API for delete a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: path
          name: id
          type: integer
          required: true
          description: "ID of the transaction to get"
      produces:
        - application/json
      responses:
        "204":
          description: User Transaction deleted successfully
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      transactionData:
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          balance:
            type: number
          detail:
            type: object
            properties:
              typeOfTransaction:
                type: string
              category:
                type: string
              wording:
                type: string
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      wording:
        type: string
